# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    # Debugging step to list the contents of the directory
    - name: List directory contents
      run: ls -al my-catalog
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'my-catalog/package-lock.json'
    - name: Use azure creds
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: npm install
      working-directory: my-catalog
    - run: npm run build
      working-directory: my-catalog
    - name: List directory contents domains
      run: ls -al my-catalog/domains
    - name: List directory contents events
      run: ls -al my-catalog/events
    - name: List directory contents public
      run: ls -al my-catalog/public
    - name: List directory contents services
      run: ls -al my-catalog/public
    - name: List directory contents Out
      run: ls -al my-catalog/out
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name lrneventcatsaeundgrf --auth-mode key -d '$web' -s my-catalog/out --overwrite
    # - name: Purge CDN endpoint
    #   uses: azure/CLI@v1
    #   with:
    #     inlineScript: |
    #        az cdn endpoint purge --content-paths  "/*" --profile-name "CDN_PROFILE_NAME" --name "CDN_ENDPOINT" --resource-group "lrn-eventcatalog-rg"
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
