# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    # Debugging step to list the contents of the directory
    - name: List directory contents
      run: ls -al my-catalog
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'my-catalog/package-lock.json'
    - run: npm install
      working-directory: my-catalog
    - run: npm run build
      working-directory: my-catalog
    - name: List directory contents domains
      run: ls -al my-catalog/domains
    - name: List directory contents events
      run: ls -al my-catalog/events
    - name: List directory contents public
      run: ls -al my-catalog/public
    - name: List directory contents services
      run: ls -al my-catalog/public
    - name: List directory contents Out
      run: ls -al my-catalog/out

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: bacongobbler/azure-blob-storage-upload-action@v1.1
      with:
        source_dir: 'my-catalog/out' # replace with your directory path
        container_name: $web
        connection_string: 'DefaultEndpointsProtocol=https;AccountName=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }};AccountKey=${{ secrets.AZURE_SECRET }};EndpointSuffix=core.windows.net'
        sync: true
